name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # ใช้ self-hosted runner ที่เราตั้งค่าไว้

    steps:
      - name: Deploy to Kubernetes
        shell: pwsh
        run: |
          $yamlContent = @"
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nodejs-app-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nodejs-app
            template:
              metadata:
                labels:
                  app: nodejs-app
              spec:
                containers:
                - name: nodejs-app
                  image: <your-dockerhub-username>/nodejs-app:latest
                  ports:
                  - containerPort: 3000
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: nodejs-app-service
          spec:
            selector:
              app: nodejs-app
            ports:
            - protocol: TCP
              port: 80
              targetPort: 3000
            type: NodePort # NodePort เหมาะกับ Docker Desktop
          "@

          $yamlContent | Out-File -FilePath deployment.yaml
          kubectl apply -f deployment.yaml